In [123]:
import numpy as np
import cv2

matrix = np.array([[0,1,0],
                   [1,-4,1],
                   [0,1,0]])

"""matrix = np.array([[0,0,0,0,0],
                   [0,0,1,0,0],
                   [0,1,-4,1,0],
                   [0,0,1,0,0],
                   [0,0,0,0,0]])"""

img = np.array([[0,0,0,0,0,0,0],
                [0,1,2,3,4,5,0],
                [0,0,1,3,4,0,0],
                [0,1,1,3,2,0,0],
                [0,0,0,4,5,6,0],
                [0,1,0,7,8,0,0],
                [0,0,0,0,0,0,0]])

resultado = np.zeros((5,5), dtype='uint8')

matrix_height = matrix.shape[0]
matrix_width = matrix.shape[1]

In [119]:
soma = 0
for l in range(5):
    for k in range(5):
        for i in range(matrix_height):
            for j in range(matrix_width):
                soma += (matrix[i,j] * img[i+l,j+k])

        print(soma)
        resultado[l,k] = soma 
        soma = 0

1
4
8
7
4
5
11
15
17
11
1
8
17
22
15
3
13
21
20
10
0
4
9
15
11


In [120]:
resultado

array([[ 1,  4,  8,  7,  4],
       [ 5, 11, 15, 17, 11],
       [ 1,  8, 17, 22, 15],
       [ 3, 13, 21, 20, 10],
       [ 0,  4,  9, 15, 11]], dtype=uint8)

## Aplicando a convolução a uma imagem

In [137]:
#Carregando a imagem
path = 'kid kakashi.png'
img = cv2.imread(path)

img_height = img.shape[0]
img_width = img.shape[1]

#Transformando em escala de cinza
gray = np.zeros(img.shape[:2], dtype = 'uint8')

for i in range(img_height):
    for j in range(img_width):
        gray[i][j] = sum(img[i][j])//3
        
cv2.imshow('Gray', gray)
cv2.waitKey()

#Criando uma borda de zeros
imagem_com_borda = cv2.copyMakeBorder(gray, 1,1,1,1, cv2.BORDER_CONSTANT, value = 0)

In [85]:
cv2.imshow('Imagem com borda', imagem_com_borda)
cv2.waitKey()

-1

In [140]:
soma = 0
imagem_resultante = np.zeros((img.shape[0], img.shape[1]), dtype=np.uint8)
print(imagem_resultante)

for l in range(img_height):
    for k in range(img_width):
        for i in range(matrix_height):
            for j in range(matrix_width):
                soma += (matrix[i,j] * imagem_com_borda[i+l,j+k])
        
        if (soma<=0):
            soma = soma * -1
        elif (soma > 255):
            soma = 255
            
        imagem_resultante[l,k] = soma
        soma = 0

cv2.imshow('Gray', gray)
cv2.imshow('Resultado', imagem_resultante)
cv2.waitKey()


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


-1

In [55]:
imagem_resultante = np.zeros((img_height, img_width), dtype=np.uint8)
cv2.imshow('Resultado', imagem_resultante)
cv2.waitKey()

-1