In [87]:
import cv2
import numpy as np

#Criando uma imagem de teste
imagem_teste = np.array([[1,1,1,1,0,0,0,0,0],
                         [1,1,1,0,0,0,0,0,0],
                         [1,1,1,1,0,0,1,0,0],
                         [0,0,1,1,1,1,1,0,0],
                         [0,0,1,1,1,1,1,0,0],
                         [0,0,1,1,1,1,1,0,0],
                         [0,0,1,0,0,0,1,1,1],
                         [0,0,0,0,0,0,1,1,1],
                         [0,0,0,0,0,0,1,1,1]],
                         dtype='uint8')

#Criando o kernel 3x3 com 1's
kernel = np.array([[255,255,255],
                   [255,255,255],
                   [255,255,255]], dtype='uint8')

kernel_height = kernel.shape[0]
kernel_width = kernel.shape[1]

In [88]:
#Criando a imagem de saída
eroded_img = np.zeros((9,9), dtype='uint8')

#Fazendo a erosão
for l in range(7):
    for k in range(7):
        flag = True
        for i in range(kernel_height):
            for j in range(kernel_width):
                if (kernel[i,j] != imagem_teste[i+l,j+k]) and (kernel[i,j] == 1):
                    flag = False
            if (flag == False):
                break
        if (flag == True):
            eroded_img[l+1,k+1] = 1
            
print(eroded_img)

[[0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 1 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0]]


## Fazendo pra valer

In [113]:
#Importando a imagem e deixando ela em preto e branco
path = 'lowcontrast.jpg'
img = cv2.imread(path, 0)
threshold, img_thresh = cv2.threshold(img, 225, 255, cv2.THRESH_BINARY_INV)
img_height = img.shape[0]
img_width = img.shape[1]

#Criando o kernel 3x3 com 1's
kernel = np.array([[255,255,255],
                   [255,255,255],
                   [255,255,255]], dtype='uint8')

kernel_height = kernel.shape[0]
kernel_width = kernel.shape[1]

#Criando a imagem de saída
eroded_img = np.zeros(img.shape[:2], dtype='uint8')


#Fazendo a erosão
for l in range(img_height - 2):
    for k in range(img_width - 2):
        flag = True
        for i in range(kernel_height):
            for j in range(kernel_width):
                if (kernel[i,j] != img_thresh[i+l,j+k]) and (kernel[i,j] == 255):
                    flag = False
            if (flag == False):
                break
        if (flag == True):
            eroded_img[l+1,k+1] = 255


print(eroded_img)
cv2.imshow('Original',img_thresh)
cv2.imshow('Eroded',eroded_img)
cv2.waitKey()

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


-1

[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
