In [7]:
import cv2
import numpy as np

kernel_size = int(input('Insira a ordem do kernel: '))
tipo_kernel = input('Elemento estruturante em cruz ou completo? ')

#Importando a imagem e deixando ela em preto e branco
path = 'buraco no quadro.jpeg'
img = cv2.imread(path, 0)
threshold, img_thresh = cv2.threshold(img, 100, 255, cv2.THRESH_BINARY)
img_height = img.shape[0]
img_width = img.shape[1]

#Criando o kernel quadrado com a ordem e o elemento estruturante pedidos pelo usuário
if (tipo_kernel == 'completo'):
    kernel = np.ones((kernel_size,kernel_size), dtype='uint8')
    kernel = kernel * 255
elif (tipo_kernel == 'cruz'):
    kernel = np.zeros((kernel_size,kernel_size), dtype='uint8')
    mid = kernel_size // 2
    for i in range(kernel_size):
        kernel[i, mid] = 255
        kernel[mid, i] = 255
    
print(kernel)

kernel_height = kernel.shape[0]
kernel_width = kernel.shape[1]


#Criando a imagem de saída
dilated_img = np.zeros(img.shape[:2], dtype='uint8')

#Fazendo a dilatação
for l in range(img_height - (kernel_size-1)):
    for k in range(img_width - (kernel_size-1)):
        for i in range(kernel_height):
            for j in range(kernel_width):
                if (kernel[i,j] == img_thresh[i+l,j+k]) and (kernel[i,j] == 255):
                    dilated_img[l+1,k+1] = 255
                    break

#Criando a imagem de saída
closed_img = np.zeros(img.shape[:2], dtype='uint8')

#Fazendo a erosão
for l in range(img_height - (kernel_size-1)):
    for k in range(img_width - (kernel_size-1)):
        flag = True
        for i in range(kernel_height):
            for j in range(kernel_width):
                if (kernel[i,j] != dilated_img[i+l,j+k]) and (kernel[i,j] == 255):
                    flag = False
            if (flag == False):
                break
        if (flag == True):
            closed_img[l+1,k+1] = 255
            
                    
cv2.imshow('Original',img_thresh)
cv2.imshow('Dilated',dilated_img)  
cv2.imshow('Closed',closed_img)
cv2.waitKey()

Insira a ordem do kernel: 5
Elemento estruturante em cruz ou completo? cruz
[[  0   0 255   0   0]
 [  0   0 255   0   0]
 [255 255 255 255 255]
 [  0   0 255   0   0]
 [  0   0 255   0   0]]


-1