In [1]:
import cv2
import numpy as np

#Criando uma imagem de teste
imagem_teste = np.array([[0,0,0,0,0,0,0,0,0],
                         [0,0,0,0,0,0,0,0,0],
                         [0,0,0,0,0,0,0,0,0],
                         [0,0,1,1,1,1,1,0,0],
                         [0,0,1,1,1,1,1,0,0],
                         [0,0,1,1,1,1,1,0,0],
                         [0,0,0,0,0,0,0,0,0],
                         [0,0,0,0,0,0,0,0,0],
                         [0,0,0,0,0,0,0,0,0]],
                         dtype='uint8')

kernel_teste = np.array([[0,1,0],
                         [1,1,1],
                         [0,1,0]])

kernel_teste_height = kernel_teste.shape[0]
kernel_teste_width = kernel_teste.shape[1]

In [2]:
dilated_img = np.zeros((9,9), dtype='uint8')


for l in range(7):
    for k in range(7):
        for i in range(kernel_teste_height):
            for j in range(kernel_teste_width):
                if (kernel_teste[i,j] == imagem_teste[i+l,j+k]) and (kernel_teste[i,j] == 1):
                    dilated_img[l+1,k+1] = 1
                    break

In [3]:
dilated_img

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=uint8)

## Fazendo pra valer

In [10]:
#Importando a imagem e deixando ela em preto e branco
path = 'lowcontrast.jpg'
img = cv2.imread(path, 0)
threshold, img_thresh = cv2.threshold(img, 225, 255, cv2.THRESH_BINARY_INV)
img_height = img.shape[0]
img_width = img.shape[1]

#Criando o kernel 3x3 com 1's
kernel = np.array([[255,255,255],
                   [255,255,255],
                   [255,255,255]], dtype='uint8')

kernel_height = kernel.shape[0]
kernel_width = kernel.shape[1]

#Criando a imagem de saída
dilated_img = np.zeros(img.shape[:2], dtype='uint8')

#Fazendo a dilatação
for l in range(img_height - 2):
    for k in range(img_width - 2):
        for i in range(kernel_teste_height):
            for j in range(kernel_teste_width):
                if (kernel[i,j] == img_thresh[i+l,j+k]) and (kernel[i,j] == 255):
                    dilated_img[l+1,k+1] = 255
                    break
                    
cv2.imshow('Original',img_thresh)
cv2.imshow('Dilated',dilated_img)
cv2.waitKey()

-1

## Automatizando

In [51]:
kernel_size = int(input('Insira a ordem do kernel: '))
tipo_kernel = input('Elemento estruturante em cruz ou completo? ')

#Importando a imagem e deixando ela em preto e branco
path = 'lowcontrast.jpg'
img = cv2.imread(path, 0)
threshold, img_thresh = cv2.threshold(img, 225, 255, cv2.THRESH_BINARY_INV)
img_height = img.shape[0]
img_width = img.shape[1]

#Criando o kernel quadrado com a ordem e o elemento estruturante pedidos pelo usuário
if (tipo_kernel == 'completo'):
    kernel = np.ones((kernel_size,kernel_size), dtype='uint8')
    kernel = kernel * 255
elif (tipo_kernel == 'cruz'):
    kernel = np.zeros((kernel_size,kernel_size), dtype='uint8')
    mid = kernel_size // 2
    for i in range(kernel_size):
        kernel[i, mid] = 255
        kernel[mid, i] = 255
    
print(kernel)

kernel_height = kernel.shape[0]
kernel_width = kernel.shape[1]

#Criando a imagem de saída
dilated_img = np.zeros(img.shape[:2], dtype='uint8')

#Fazendo a dilatação
for l in range(img_height - (kernel_size-1)):
    for k in range(img_width - (kernel_size-1)):
        for i in range(kernel_height):
            for j in range(kernel_width):
                if (kernel[i,j] == img_thresh[i+l,j+k]) and (kernel[i,j] == 255):
                    dilated_img[l+1,k+1] = 255
                    break
                    
cv2.imshow('Original',img_thresh)
cv2.imshow('Dilated',dilated_img)
cv2.waitKey()

Insira a ordem do kernel: 5
Elemento estruturante em cruz ou completo? completo
[[255 255 255 255 255]
 [255 255 255 255 255]
 [255 255 255 255 255]
 [255 255 255 255 255]
 [255 255 255 255 255]]


-1